---
services:
  flask:
    image: aputra/flask:0.1.0
    build:
      context: flask
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
    - "7070:8080"
    env_file:
    - ./flask/dev.env
    secrets:
      - api_key
      - source: api_key
        target: /api_key.txt
    configs:
      - source: my_config
        target: /config-dev-v2.yaml
    environment:
      - APP_VERSION=0.1.0
      - DB_PASSWORD
      - APP_TOKEN=${APP_TOKEN}
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
    volumes:
      - ./flask/config-dev.yaml:/config-dev.yaml
      # - ./flask/my-data:/data
      - flask-data:/data
      - ./flask:/app
    networks:
      - private

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private
secrets:
  api_key:
    file: ./flask/api_key.txt
  pg_password:
    file: ./pg_password.txt
configs:
  my_config:
    file: ./flask/config-dev.yaml
volumes:
  flask-data:
  postgres-data:

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/19"
          gateway: "10.0.0.1"


